version: '3'
services:
  headless-store:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8001:4200
      - 8003:3333
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - url-ecommerce

volumes:
  node_modules:

networks:
  url-ecommerce:
    driver: bridge