# Start from node base image
FROM node:14.18-alpine

# Set the current working directory inside the container
WORKDIR /usr/src/app

# Copy package.json, yarn.lock files and download deps
COPY package.json yarn.lock ./
RUN yarn global add @angular/cli
RUN yarn global add @nxpm/cli@latest

# Copy sources to the working directory
COPY . .

# Set the Node environment
ARG node_env=development
ENV NODE_ENV $node_env
RUN ./node_modules/.bin/nx version

EXPOSE 4200
EXPOSE 3333
# Run the app
CMD ["npm", "run", "serve-url-storefront-all"]